[package]
name = "md2html"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
pulldown-cmark = "0.9"
comrak = "0.21"

[[bench]]
name = "markdown_parsers"
harness = false