name: Security Audit

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    # Run security audit weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-audit-${{ hashFiles('**/Cargo.lock') }}

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run security audit
      run: cargo audit

    - name: Check for unsafe code
      run: |
        echo "=== Checking for unsafe code blocks ==="
        # Find unsafe blocks and report them
        unsafe_count=$(grep -r "unsafe" src/ --include="*.rs" | wc -l || echo "0")
        echo "Found $unsafe_count unsafe blocks in source code"
        
        if [ "$unsafe_count" -gt 0 ]; then
          echo "Unsafe blocks found:"
          grep -r "unsafe" src/ --include="*.rs" || true
          echo ""
          echo "⚠️  This project contains unsafe code. Please ensure it's properly documented and justified."
        else
          echo "✅ No unsafe code found"
        fi

    - name: Check dependencies for known vulnerabilities
      run: |
        echo "=== Dependency Security Check ==="
        cargo audit --db ./advisory-db || cargo audit